# Generated by Django 3.0.7 on 2020-07-16 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='benefactor',
        ),
        migrations.RemoveField(
            model_name='beneficiario',
            name='beneficio',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DetalleBeneficiario',
            fields=[
                ('idDetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.CharField(max_length=10)),
                ('benefactor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Benefactor')),
                ('beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Beneficiario')),
                ('beneficio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Beneficio')),
            ],
        ),
    ]
